# Generated by Django 3.2.10 on 2021-12-17 06:54

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[A-Za-z0-9@#$%^&+=]{8,}', message='The password must contain at least one in  A-Z and a-z, 0-9 and special character.')])),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('profile_img', models.ImageField(blank=True, default='Images/profile/default.png', upload_to='Images/profile')),
                ('deactivate', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('user_type', models.IntegerField(choices=[(1, 'Instructor'), (2, 'Trainee'), (3, 'Admin')], default=2)),
                ('address', models.CharField(max_length=150)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[-+]?([1-8]?\\d(\\.\\d+)?|90(\\.0+)?)$', message='Not a valid latitude')])),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^\\s*[-+]?(180(\\.0+)?|((1[0-7]\\d)|([1-9]?\\d))(\\.\\d+)?)$', message='Not a valid longitude')])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
