# Generated by Django 3.1.1 on 2021-04-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='classinstructor',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
    ]
