# Generated by Django 3.1.1 on 2021-04-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0002_auto_20210408_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinstructor',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Fee'),
        ),
    ]
