# Generated by Django 3.1.1 on 2021-05-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0003_auto_20210410_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Completed'), ('3', 'Rejected')], max_length=1),
        ),
    ]
