# Generated by Django 3.2.9 on 2022-02-08 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0005_booking_kids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myBooking', to='Appointment.booking'),
        ),
    ]
