# Generated by Django 3.2.9 on 2022-01-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StripePayment', '0002_stripeaccount_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeaccount',
            name='created_at',
        ),
    ]
