# Generated by Django 3.1.1 on 2021-04-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210331_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='url',
            field=models.CharField(default='demo', max_length=150),
            preserve_default=False,
        ),
    ]
