# Generated by Django 3.1.1 on 2021-04-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User__user', 'verbose_name_plural': 'Users'},
        ),
    ]
