# Generated by Django 3.1.1 on 2021-04-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210408_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User__user12', 'verbose_name_plural': 'Users12'},
        ),
    ]
