# Generated by Django 3.1.1 on 2021-04-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210408_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User__users', 'verbose_name_plural': 'Users'},
        ),
    ]
