# Generated by Django 3.1.1 on 2021-04-08 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210408_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'User__Instructor', 'verbose_name_plural': 'Instructor Profile'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'User__students', 'verbose_name_plural': 'Students Profile'},
        ),
    ]
