# Generated by Django 3.1.1 on 2021-04-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210408_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewrate',
            options={'verbose_name': 'User__review', 'verbose_name_plural': "Instructor's Review"},
        ),
    ]
