# Generated by Django 3.1.1 on 2021-04-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210408_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructor Profile'},
        ),
        migrations.AlterModelOptions(
            name='reviewrate',
            options={'verbose_name': 'Review', 'verbose_name_plural': "Instructor's Review"},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Students', 'verbose_name_plural': 'Students Profile'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Instructor'), (2, 'Trainee'), (3, 'Admin')], default=2, editable=False),
        ),
    ]
