# Generated by Django 3.1.1 on 2021-05-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210408_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, default='Images/profile/default.png', upload_to='Images/profile'),
        ),
    ]
