# Generated by Django 3.1.1 on 2021-06-11 11:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210514_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekTimeSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_startTime_slot', models.TimeField(default=django.utils.timezone.now, error_messages={'error': 'Choose a valid time format.'}, help_text='Choose monday start working time slot or set it current time.', verbose_name='Monday start time slot')),
                ('monday_endTime_slot', models.TimeField(default=django.utils.timezone.now, error_messages={'error': 'Choose a valid time format.'}, help_text='Choose monday start working time slot or set it current time.', verbose_name='Monday end time slot')),
                ('tuesday_startTime_slot', models.TimeField(default=django.utils.timezone.now, error_messages={'error': 'Choose a valid time format.'}, help_text='Choose tuesday start working time slot or set it current time.', verbose_name='Tuesday start time slot')),
                ('tuesday_endTime_slot', models.TimeField(default=django.utils.timezone.now, error_messages={'error': 'Choose a valid time format.'}, help_text='Choose tuesday start working time slot or set it current time.', verbose_name='Tuesday end time slot')),
                ('wednesday_startTime_slot', models.TimeField(default=django.utils.timezone.now, error_messages={'error': 'Choose a valid time format.'}, help_text='Choose wednesday start working time slot or set it current time.', verbose_name='Wednesday start time slot')),
                ('wednesday_endTime_slot', models.TimeField(default=django.utils.timezone.now, error_messages={'error': 'Choose a valid time format.'}, help_text='Choose wednesday start working time slot or set it current time.', verbose_name='Wednesday end time slot')),
                ('thursday_startTime_slot', models.TimeField(default=django.utils.timezone.now, error_messages={'error': 'Choose a valid time format.'}, help_text='Choose thursday start working time slot or set it current time.', verbose_name='Thursday start time slot')),
                ('thursday_endTime_slot', models.TimeField(default=django.utils.timezone.now, error_messages={'error': 'Choose a valid time format.'}, help_text='Choose thursday start working time slot or set it current time.', verbose_name='Thursday end time slot')),
                ('friday_startTime_slot', models.TimeField(default=django.utils.timezone.now, error_messages={'error': 'Choose a valid time format.'}, help_text='Choose friday start working time slot or set it current time.', verbose_name='Friday start time slot')),
                ('friday_endTime_slot', models.TimeField(default=django.utils.timezone.now, error_messages={'error': 'Choose a valid time format.'}, help_text='Choose friday start working time slot or set it current time.', verbose_name='Friday end time slot')),
                ('saturday_startTime_slot', models.TimeField(default=django.utils.timezone.now, error_messages={'error': 'Choose a valid time format.'}, help_text='Choose saturday start working time slot or set it current time.', verbose_name='Saturday start time slot')),
                ('saturday_endTime_slot', models.TimeField(default=django.utils.timezone.now, error_messages={'error': 'Choose a valid time format.'}, help_text='Choose saturday start working time slot or set it current time.', verbose_name='Saturday end time slot')),
                ('sunday_startTime_slot', models.TimeField(default=django.utils.timezone.now, error_messages={'error': 'Choose a valid time format.'}, help_text='Choose sunday start working time slot or set it current time.', verbose_name='Sunday start time slot')),
                ('sunday_endTime_slot', models.TimeField(default=django.utils.timezone.now, error_messages={'error': 'Choose a valid time format.'}, help_text='Choose sunday start working time slot or set it current time.', verbose_name='Sunday end time slot')),
                ('instructor', models.ForeignKey(error_messages={'error': 'Instructor must be required.'}, help_text='Instructor required.', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='Instructor slots')),
            ],
            options={
                'verbose_name': 'Weekly Time Slot',
                'verbose_name_plural': 'Weekly Time Slots',
            },
        ),
    ]
