# Generated by Django 3.1.1 on 2021-06-19 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210618_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[(1, 'monday'), (2, 'tuesday'), (3, 'wednesday'), (4, 'thursday'), (5, 'friday'), (6, 'saturday'), (7, 'sunday')], max_length=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('instructor', models.ForeignKey(error_messages={'error': 'Instructor must required.'}, help_text='Instructor required.', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='Instructor slots')),
            ],
            options={
                'verbose_name': 'Break Time',
                'verbose_name_plural': 'Break Time',
            },
        ),
    ]
