# Generated by Django 3.1.1 on 2021-12-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20210619_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dateofbirth',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mother_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
