# Generated by Django 3.1.1 on 2021-12-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20211224_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dateofbirth',
            new_name='DateOfBirth',
        ),
    ]
