# Generated by Django 3.2.9 on 2021-12-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_user_instructor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='instructor_id',
        ),
    ]
