# Generated by Django 3.2.9 on 2021-12-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_remove_user_instructor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instructor_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
