# Generated by Django 3.2.9 on 2021-12-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_user_instructor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='instructor_id',
            new_name='inst_id',
        ),
    ]
