# Generated by Django 3.2.9 on 2022-01-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_rename_instructor_id_user_inst_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
