# Generated by Django 3.2.9 on 2022-01-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_user_mobile_no'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
