# Generated by Django 3.2.9 on 2022-01-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
